use_frameworks!

platform :ios, '8.0'

target 'SubComponentC_Example' do
  pod 'SubComponentC', :path => '../'
  pod 'MGJRouter', '~>0.9.0'

  target 'SubComponentC_Tests' do
    inherit! :search_paths

    
  end
end
